services:
  mc:
    image: itzg/minecraft-server:java17
    ports:
      - "25565:25565"
    environment:
      EULA: "true"
      CF_API_KEY: ${CF_API_KEY}
      MOD_PLATFORM: AUTO_CURSEFORGE
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-gravitas2/files/5501962
      MEMORY: 8G
      USE_AIKAR_FLAGS: true
      # Server properties
      MOTD: Running %MODPACK_NAME% version %env:MODPACK_VERSION%
      SNOOPER_ENABLED: false
      ALLOW_FLIGHT: true
      SERVER_NAME: mc.lorwp.cc %MODPACK_NAME%
      DIFFICULTY: normal
      ENABLE_WHITELIST: true
      WHITELIST: |
        lorwp
        NoxVS
        DoctorTimeLord
        Jackraxxus
        Isratosh
        Thunder22
        Pink______
        NarNarMoth
        Nimowa
        Davethwave
        kinnebian
      EXISTING_WHITELIST_FILE: SYNCHRONIZE
      OPS: |
        lorwp
        Isratosh
      EXISTING_OPS_FILE: SYNCHRONIZE
    restart: unless-stopped
    env_file:
      - ./mc.env.example
    volumes:
      - ./data/gravitas2:/data
      - ./downloads:/downloads
      - ./mods:/mods
      - /etc/timezone:/etc/timezone:ro
      - ./config:/config
  mc-backup:
    container_name: mc-backup
    image: itzg/mc-backup
    depends_on:
      mc:
        condition: service_healthy
    environment:
      BACKUP_INTERVAL: 1h
      RCON_HOST: mc
      # since this service waits for mc to be healthy, no initial delay is needed
      INITIAL_DELAY: 0
      BACKUP_METHOD: restic
      # RESTIC_PASSWORD and RESTIC_REPOSITORY should be set in restic.env
    restart: unless-stopped
    env_file:
        - ./restic.env
