services:
  mc:
    image: itzg/minecraft-server:java17
    ports:
      - "25565:25565"
    environment:
      EULA: "true"
      ENABLE_RCON: true
      CF_API_KEY: ${CF_API_KEY}
      TYPE: FORGE
      VERSION: "1.20.1"
      FORGE_VERSION: "47.2.6"
      MEMORY: 8G
      MODRINTH_PROJECTS: |
        sdlink
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
      USE_AIKAR_FLAGS: true
      # Server properties
      MOTD: Running %MODPACK_NAME% version %env:MODPACK_VERSION%
      SNOOPER_ENABLED: false
      ALLOW_FLIGHT: true
      SERVER_NAME: mc.lorwp.cc %MODPACK_NAME%
      DIFFICULTY: normal
      ENABLE_WHITELIST: true
      WHITELIST: |
        lorwp
        NoxVS
        DoctorTimeLord
        Jackraxxus
        Isratosh
        Thunder22
        Pink______
        NarNarMoth
        Nimowa
        Davethwave
        kinnebian
        Gaston6828
        walterclements69
        nabski
        Ayame_Pup
        Arianot
        ArcaneToxin
      EXISTING_WHITELIST_FILE: SYNCHRONIZE
      OPS: |
        lorwp
        Isratosh
      EXISTING_OPS_FILE: SYNCHRONIZE
    restart: unless-stopped
    env_file:
      - ./mc.env
    volumes:
      - ./data/gravitas2:/data
      - ./downloads:/downloads
      - ./mods:/mods
      - /etc/timezone:/etc/timezone:ro
      - ./config:/config
  mc-backup:
    container_name: mc-backup
    image: itzg/mc-backup
    environment:
      TZ: Australia/Melbourne
      BACKUP_INTERVAL: 1h
      RCON_HOST: mc
      INITIAL_DELAY: 20
      BACKUP_METHOD: restic
      # RESTIC_PASSWORD and RESTIC_REPOSITORY should be set in restic.env
      RESTIC_HOSTNAME: "tg_gravitas2"
    restart: unless-stopped
    env_file:
        - ./restic.env
    volumes:
      - ./data/gravitas2:/data:ro
